/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradle;

import java.util.ArrayList;

import gradle.components.inputs.Input;
import gradle.components.inputs.ListPasswordPage;
import gradle.components.inputs.SelectInput;
import gradle.components.outputs.HLine;
import gradle.components.outputs.Label;
import gradle.components.outputs.Space;
import gradle.models.DataPassword;
import gradle.models.PasswordStore;
import gradle.pages.InputPage;
import gradle.pages.MainPage;

// import java.security.NoSuchAlgorithmException;

// import gradle.components.outputs.HLine;
// import gradle.components.outputs.Label;
// import gradle.components.outputs.Space;
// import gradle.pages.InputPage;
// import gradle.components.inputs.Input;
// import gradle.components.inputs.SelectInput;
// import models.PasswordStore;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        try {
            DataPassword.loadCSVData();
            MainPage mainPage = new MainPage(80);
            mainPage.draw();

            // Your application logic here (e.g., password input, display)
            // Use DataPassword.passData to manage password data

            // Save password data on exit (before exiting the application)
            DataPassword.saveCSVData();
            // new InputPage("Inputan Pas", 50).draw();
            // // new InputPage("Inssp", 50).draw();
            // new ListPasswordPage("gE", 50).drawContent();
            // new HLine(50).draw();
            // new Space(50).draw();
            // new Label(50, "Uji Coba komponen yang dibuat").draw();
            // new Space(50).draw();

            // new HLine(50).draw();
            // new Space(50).draw();
            // Input input = new Input("Masukkan nama");
            // Input input2 = new Input("Usia anda");
            // input.readInput();
            // String nama = input.getValue();
            // input2.readInput();
            // int usia = input2.getValueInt();

            // new Space(50).draw();

            // String[] choices = { "Pilihan 1", "Pilihan 2", "Pilihan 3", "Pilihan 4" };
            // SelectInput selectInput = new SelectInput("Inputkan pilihan anda:", 70,
            // choices);
            // selectInput.draw();
            // int value = selectInput.getValue();
            // new Space(50).draw();
            // new HLine(50).draw();
            // new Space(50).draw();
            // new Label(50, "Nama anda: " + nama).draw();
            // new Label(50, "Usia anda: " + usia).draw();
            // new Label(50, "Anda memilih menu: " + value).draw();

        } catch (Exception e) {
            e.printStackTrace();
        }

    }
}
